### PR TITLE
Fix double free when discovering search providers

### PR DESCRIPTION
**Pull request by andrunko**
This fixes a crash when clicking on Search on latest master.

https://phabricator.endlessm.com/T25338

### CODE REVIEW

**Comment by andrunko** [comment]
https://phabricator.endlessm.com/T25338

**Comment by andrunko** [comment]
See also the comment from @pwithnall on https://github.com/endlessm/gnome-control-center/pull/174/commits/47e88c1616a0a7451cbd28ad82bfd18a43b7290c

**Comment by pwithnall** [comment]
I’ve already reviewed this and think it’s OK, but it’s probably an idea to get a second review from @GeorgesStavracas.

**Comment by andrunko** [comment]
Thanks - updated commit msg, merging.

**Pull request merged**
