### PR TITLE
T31550

### PR DESCRIPTION
**Pull request by GeorgesStavracas**
* pick b0d5528c4 bluetooth: set switch off when BT airplane mode is enabled
 * pick 831f0bc32 eos: Move the shell bar to the bottom of the background preview
   * squash 8224df7f8 display: adjust output thumbnail to bottom panel
 * pick c16700aab region: update the locale format along with the language when it changes
 * pick 48f68dbe4 user-accounts: allow empty/weak passwords
 * pick 740aa06c4 panels: lock: Disable lock screen when autologin is enabled
 * pick dc1d78882 user-accounts: Fall back to "user" as the default login name
 * pick 557a51f07 user-accounts: Allow account creation when name contains no ASCII
 * pick b5d42247e user-accounts: Allow to create a user without a password
 * pick ddc53de57 user-accounts: Allow to remove the password for a user
 * pick d2fb14036 user-accounts: Show the correct password mode when changing it
 * pick 6a1553d20 user-accounts: Allow to change the password mode for oneself
 * pick 7dc92dbee Populate language chooser with FBE vendor config file
 * pick a90b44da5 info-overview: add link for license attribution document
 * pick 369330dd5 user panel, password: add fallback kbd layout if necessary
 * pick 634f76c25 updates: Introduce Automatic Updates panel
   * fixup a50897c1b fixup! updates: Introduce Automatic Updates panel
   * fixup 8946bb591 fixup! updates: Introduce Automatic Updates panel
   * fixup cf3835d54 fixup! updates: Introduce Automatic Updates panel
   * squash 6442303ff updates: Use connection.allow-downloads setting
   * squash 582be5fc5 updates: Fix tariff builder failure with non-UTC timezones
   * squash 1d65350ea updates: Add some additional debug assertions
 * pick 282e74e9d Don't declare StartupNotify=true in panel-specific desktop files
 * pick 49cea5486 panels: Add X-GNOME-UsesNotifications to several desktop files
 * pick 80cb0910b user-accounts: Limit to 80 characters
 * pick 3c061c4aa background: also monitor the wallpapers directory
 * pick eb887d9d8 applications: Use "Open in App Center" instead of "Open in Software"
 * pick 018a93c12 applications: hide “Show in App Center” for App Center
 * pick 8336a9def privacy: Add metrics panel controlling metrics service integration
   * fixup 3933c776e fixup! privacy: Add metrics panel controlling metrics service integration
 * pick f8736d72d Debian's adduser doesn't allow uppercase letters by default.
 * pick be715b189 user-accounts: Fix a critical warning if loading a cursor fails
 * pick 1c78ffa27 privacy: Mention that system apps can always use the camera/microphone
 * pick 544933126 updates: Factor out a variable
 * pick af79167c5 updates: Send a metric when automatic updates settings change
   * fixup 711143588 fixup! updates: Send a metric when automatic updates settings change
 * pick 81f0c3f9b Add translation support for several new languages
 * pick 08a709d52 Add Transifex translation infrastructure

# Dropped

 * pick 2cde55abe region: replace the "Login Screen" button
 
 * pick c00c03ce6 user-accounts: Allow to set up a password reminder
   * https://phabricator.endlessm.com/T31692#882871
 * pick aaab0d094 user-accounts: Hide username from new account dialog
   * As per Will's request \o/
 * pick 5e583e46b wacom: Fix a critical warning if loading a cursor fails
   * Present in 3.38.2
 * pick 4e6d1780d display: Add a method to retrieve the name of a monitor mode
 * fixup 69600ae9a fixup! display: Add a method to retrieve the name of a monitor mode
   * Mutter doesn't ship the corresponding patch anymore
 * pick 3aae789bd user-accounts: Fix ability to choose avatar
   * pick aa70440c1 Revert "user-accounts: Fix ability to choose avatar"
 * pick e5752b63e region: Change "Input Sources" label
   * pick eb01a172c Revert "region: Change "Input Sources" label"
 * pick 08a382a88 info-overview: Report Endless version instead of GNOME version
   * https://phabricator.endlessm.com/T26931
 * pick 951fdbc82 eos: Add metric for opening a panel
   * https://docs.google.com/document/d/1MMT1HTD-rZPJ7k20TYD3zX3MslSK2X_uGPB6Hxle9Kc
 * pick 8692f0a06 applications: hide "Get ____" launchers
 * pick d741697a7 applications: Filter out "eos-link-" Endless-specific webapps
 * fixup efd5c2f47 applications: Remove eos-link-* special handling
   * No remaining eos-link- launchers
 
https://phabricator.endlessm.com/T31550

### CODE REVIEW

**Comment by GeorgesStavracas** [comment]
retest this please

**Comment by GeorgesStavracas** [comment]
Build a debian package out of this, and it works as expected. Undrafting.

**Comment by GeorgesStavracas** [comment]
I've made a bold decision to drop the Endless logo patch here, so I don't have to do that as part of https://phabricator.endlessm.com/T26931. This means less work for that ticket, but also means the info panel will temporarily show the GNOME foot.

**Comment by wjt** [comment]
Nice to see that quite a few of these remaining patches were accepted upstream!

> * pick [2cde55a](https://github.com/endlessm/gnome-control-center/commit/2cde55abeaa627d3645f2c755288724d7bdcd38f) region: replace the "Login Screen" button

Tempted to say ‘drop’. This was Soft-rejected upstream due to the panel being redesigned. https://gitlab.gnome.org/GNOME/gnome-control-center/-/merge_requests/821

> * pick [c00c03c](https://github.com/endlessm/gnome-control-center/commit/c00c03ce6df28bc8a7cc5a8ab638114b3c601c6c) user-accounts: Allow to set up a password reminder

Per https://phabricator.endlessm.com/T31692#882871 we can drop this.

> * pick [aaab0d0](https://github.com/endlessm/gnome-control-center/commit/aaab0d09422bb16db295ddaf5441b0836d522be5) user-accounts: Hide username from new account dialog
> * pick [dc1d788](https://github.com/endlessm/gnome-control-center/commit/dc1d78882cdf1517cd55984431bca65c6140bebe) user-accounts: Fall back to "user" as the default login name
> * pick [557a51f](https://github.com/endlessm/gnome-control-center/commit/557a51f07e4f1e73c81382dfd2de3376f0f04e17) user-accounts: Allow account creation when name contains no ASCII

Drop these three. Not allowing the user to configure a username is not an important differentiator for Endless OS. It does seem desirable to not *force* the user to pick a username, so keep whatever is necessary to always generate a username, even if it's "user".

> * pick [282e74e](https://github.com/endlessm/gnome-control-center/commit/282e74e9d8c10812b46bb548b6abb99035a5935d) Don't declare StartupNotify=true in panel-specific desktop files

If this is a useful patch, can we upstream it?

> * pick [49cea54](https://github.com/endlessm/gnome-control-center/commit/49cea5486d2f171953c40d6d0d97f034eeb80508) panels: Add X-GNOME-UsesNotifications to several desktop files

Ditto?

> * pick [d741697](https://github.com/endlessm/gnome-control-center/commit/d741697a7286785a518d31e584824d056d2af6cc) applications: Filter out "eos-link-" Endless-specific webapps
>   
>   * fixup [efd5c2f](https://github.com/endlessm/gnome-control-center/commit/efd5c2f4706dc673e02c2d9ed62e6fdf3ab1945f) applications: Remove eos-link-* special handling

Drop, we removed all these from the OS. https://phabricator.endlessm.com/T31560

**Comment by wjt** [comment]
> > * pick [aaab0d0](https://github.com/endlessm/gnome-control-center/commit/aaab0d09422bb16db295ddaf5441b0836d522be5) user-accounts: Hide username from new account dialog
> > * pick [dc1d788](https://github.com/endlessm/gnome-control-center/commit/dc1d78882cdf1517cd55984431bca65c6140bebe) user-accounts: Fall back to "user" as the default login name
> > * pick [557a51f](https://github.com/endlessm/gnome-control-center/commit/557a51f07e4f1e73c81382dfd2de3376f0f04e17) user-accounts: Allow account creation when name contains no ASCII
> 
> Drop these three. Not allowing the user to configure a username is not an important differentiator for Endless OS. It does seem desirable to not _force_ the user to pick a username, so keep whatever is necessary to always generate a username, even if it's "user".

Does this branch always generate a candidate username even if the user's full name is, eg, "Лев Дави́дович Ланда́у"? I think this is what dc1d78882cdf1517cd55984431bca65c6140bebe was doing.

**Comment by GeorgesStavracas** [comment]
> Does this branch always generate a candidate username even if the user's full name is, eg, "Лев Дави́дович Ланда́у"? I think this is what dc1d788 was doing.

It doesn't, with and without dc1d788.

**Comment by GeorgesStavracas** [comment]
I'm pushing back commits dc1d78882 and 557a51f07 because, despite not fixing the naming suggestion issue, they're probably part of it.

**Comment by wjt** [comment]
I understand from Slack that those patches do actually restore that behaviour. If so, ship it :shipit:

**Review by wjt — APPROVED** [review]

**Pull request merged**
