### PR TITLE
Update .po files

### PR DESCRIPTION
**Pull request by dbnicholson**
ninja -C _build/ gnome-control-center-2.0-update-po

Does this look at all reasonable? Should I attempt to bring back downstream translations like [this](https://github.com/endlessm/gnome-control-center/commit/b63984cdcb291c72fd92a58ff831d57d3d082365)?

Also, of particular interest to this repo is the `kab` translation. Someone added it upstream in `main` and on the `gnome-3-38` branch (where we [inherited it](https://github.com/endlessm/gnome-control-center/commit/99aa37a62480e9b6f0f98bb00d858943598de959)), but it's not on the `gnome-41` branch. Should I try to bring it back?

https://phabricator.endlessm.com/T33861

### CODE REVIEW

**Comment by wjt** [comment]
> Does this look at all reasonable?

Yep!

> Should I attempt to bring back downstream translations like [this](https://github.com/endlessm/gnome-control-center/commit/b63984cdcb291c72fd92a58ff831d57d3d082365)?

No. We discussed this on Slack but for completeness:

- We used to try to preserve our downstream translation changes. I wrote [this post](https://blogs.gnome.org/wjjt/2019/06/21/rebasing-downstream-translations/) about it. The primary reason was to adjust [tú vs usted](https://discourse.gnome.org/t/tu-usted-in-spanish-translations/748) in Spanish.
- I wrote a script to automate what Roddy used to do (apparently by hand)
- But then we had a change of course and it was decided that maintaining that change was no longer worthwhile
- So now we prefer GNOME's translations
- Which makes the "merge" easier: just push GNOME's translations into Transifex. Transifex's "translation memory" will fill in the gaps where a string has an existing translation in Endless but not in GNOME

> Also, of particular interest to this repo is the `kab` translation. Someone added it upstream in `main` and on the `gnome-3-38` branch (where we [inherited it](https://github.com/endlessm/gnome-control-center/commit/99aa37a62480e9b6f0f98bb00d858943598de959)), but it's not on the `gnome-41` branch. Should I try to bring it back?

Fascinating!

Looking at our ping data we have of the order of 20 users in Algeria, the main place where kabyle is spoken. We don't have any metrics on language use. My suggestion would be to bring it back if it takes no more than 10 minutes, and otherwise, with regret, wait till we get a newer GNOME.

**Comment by dbnicholson** [comment]
> > Does this look at all reasonable?
> 
> Yep!

Great. Shall I go forward and start pushing then?

> > Should I attempt to bring back downstream translations like [this](https://github.com/endlessm/gnome-control-center/commit/b63984cdcb291c72fd92a58ff831d57d3d082365)?
> 
> No. We discussed this on Slack but for completeness:

That all makes sense. I recall trying to help out with this a few years ago and finding the rebasing of old translations to be very painful. Glad we're not doing that anymore.

> > Also, of particular interest to this repo is the `kab` translation. Someone added it upstream in `main` and on the `gnome-3-38` branch (where we [inherited it](https://github.com/endlessm/gnome-control-center/commit/99aa37a62480e9b6f0f98bb00d858943598de959)), but it's not on the `gnome-41` branch. Should I try to bring it back?
> 
> Fascinating!
> 
> Looking at our ping data we have of the order of 20 users in Algeria, the main place where kabyle is spoken. We don't have any metrics on language use. My suggestion would be to bring it back if it takes no more than 10 minutes, and otherwise, with regret, wait till we get a newer GNOME.

I'll have to look again, but I don't think there have been any more updates since the initial translation. So, I think it should just be a single cherry pick.

**Comment by wjt** [comment]
> Shall I go forward and start pushing then?

Go forth!

**Comment by dbnicholson** [comment]
Either this is now unimportant or I added it in a different way.

**Pull request closed without merging**
