### PR TITLE
T30174 rebase on 3.37.90

### PR DESCRIPTION
**Pull request by mwleeds**
Rebase notes [here](https://docs.google.com/spreadsheets/d/1BDg22wGnU8J1GU0hxo8R6bzjbjqR6yXQsnj2lqZedm0/edit?usp=sharing)

The final commits on the branch are the only new ones:

- `fixup! display: Add a method to retrieve the name of a monitor mode`
- `Revert "Revert "Temporarily disable the canonicalization test""`
- `Debian's adduser doesn't allow uppercase letters by default.`

Left to do before this can be merged:

- [x] Get https://github.com/endlessm/mutter/pull/113 merged
- [x] Rebase the packaging branch here (see the branch `debian-T30174-rebase-3.38`)
- [] ~~Check if the links in [this commit](https://github.com/endlessm/gnome-control-center/commit/1dda36670) are still valid~~ (commit dropped as it should no longer be needed after [T25587](https://phabricator.endlessm.com/T25587))

Can be done after merge:
- [ ] ~~Look into adding a metric for overscan compensation as discussed on the ticket~~ (moved to https://phabricator.endlessm.com/T30766)

https://phabricator.endlessm.com/T30174

### CODE REVIEW

**Comment by mwleeds** [comment]
bot, retest this please

**Comment by mwleeds** [comment]
bot, retest this please

**Comment by mwleeds** [comment]
I updated the packaging branch to drop the libhandy build dependency (because there's meson logic to build it if needed).

GitHub didn't let me open a PR for the packaging branch because of the diverging history (I changed it to be based on the [Debian git branch](https://salsa.debian.org/gnome-team/gnome-control-center/-/commits/debian/master/) rather than based on tarballs). So maybe we'll have to discuss it here. The branch is `debian-T30174-rebase-3.38`.

**Comment by mwleeds** [comment]
bot, retest this please

(network-manager has been updated in OBS)

**Comment by mwleeds** [comment]
bot, retest this please

(hoping the error `libsemanage1 : Depends: libsemanage-common (= 2.8-2bem1) but 2.8-2bem2 is installed` was unrelated and the master ostree builds this afternoon passed)

**Comment by andrunko** [comment]
bot, retest this please

**Comment by mwleeds** [comment]
bot, retest this please

(Pushed Version_3.37.90 and Version_3.37.90_debian tags)

**Comment by mwleeds** [comment]
I built this locally and did some basic testing.

**Comment by mwleeds** [comment]
Re-added "Add translation support for several new languages" after realizing it shouldn't have been dropped.

**Review by GeorgesStavracas — APPROVED** [review]
LGTM

**Comment by mwleeds** [comment]
Updated this to 3.38.0, the diff from 3.37.90 was minimal, excluding translation updates:
```
2e37c9d87 build: Use non-deprecated python module to search for python
fd795a803 (tag: 3.37.92) 3.37.92
71baf068d Disable the canonicalization test
6782bc07d display: Hook to PanelOrientationManaged for accelerometer checks
c89f5ca52 display: Add panel-orientation-managed signal to CcDisplayConfig
b91a83c40 display: Add API to get the PanelOrientationManaged DisplayConfig property
1ae3ebcfb display: Use a proxy for org.gnome.Mutter.DisplayConfig
297906685 wacom: Group pad/stylus devices together with the group name
14da36860 common: Add GsdDevice API to tell whether 2 devices are grouped
eb14c5a64 wacom: Cater for multiple pads in the CcWacomPage
e50f27a96 wacom: Let CcWacomPage track pad devices
```

Updated the packaging branch as well.

**Pull request merged**
